name: EpicCustomAlerts
version: 0.1.0
api: 5.0.0
main: davidglitch04\EpicCustomAlerts\Loader
src-namespace-prefix: davidglitch04\EpicCustomAlerts
author: DavidGlitch04
website: https://github.com/DavidGlitch04